name: Deploy to Public Repo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Set up Git config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Clone public repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://github.com/nsknv/Public.git Public
          cd Public
          git checkout main
      
      - name: Copy files to public repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          rsync -av --exclude='.git' --exclude='.github' . Public/
          cd Public
          git config --global user.name "nsknv"
          git config --global user.email "nsknv@users.noreply.github.com"
          git add -A
          git commit -m "Deploy from private repo"
          git push https://x-access-token:${GH_PAT}@github.com/nsknv/Public.git main
